name: mrtnk
favicon: null
layout_spectrum: 0.71547
typography_spectrum: 0.68691
title: Home of Martins thoughts and things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-808807-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#169889'
    - '#f55a3a'
    - '#ecb83f'
    - '#cc1d3a'
    - '#a3a84f'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
