name: mrtnk
favicon: null
layout_spectrum: 0.88695
typography_spectrum: 0.70617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20676a'
    - '#eafde7'
    - '#bff031'
    - '#8ac235'
    - '#53944c'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
