name: mrtnk
favicon: null
layout_spectrum: 0.17789026000536978
typography_spectrum: 0.6273104788269848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7769944935571402
  lightness: 0.1643004270736128
  saturation: 0.31307781976647675
  rhythmicContrast: 0.6747938001062721
purpose: []
